desc "deploy build directory to github pages"
task :deploy do
  system "middleman build"
  puts "## Deploying to Github Pages"
  cp_r "source/.nojekyll", "build/.nojekyll"
  cd "build" do
    system "git add -A"
    message = "Site updated at #{Time.now.utc}"
    puts "\n## Commiting: #{message}"
    system "git commit -m \"#{message}\""
    puts "\n## Pushing generated website"
    system "git push"
    puts "\n## Github Pages deploy complete"
  end
end
